### REQUEST JWT TOKEN
POST http://localhost:8080/academics/api/auth/login
Content-Type: application/json
Accept: application/json

{ "username": "Mariozin", "password": "123" }

### Get Authenticated User
GET http://localhost:8080/academics/api/auth/user
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJMYXVyYTAxIiwiaWF0IjoxNzM3MTU1NjcxLCJleHAiOjE3MzcxNTkyNzF9.YCO0rakQAI5XIqSCWZupu3sYHm_WVfXQPfju0_kKPu0QZ1qEmSMG1OmQYg0lzZl6


### GET PRODUCTS
GET http://localhost:8080/academics/api/product/
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJNYXJpb3ppbiIsImlhdCI6MTczNzE1NDQ3OSwiZXhwIjoxNzM3MTU4MDc5fQ.8WpXbke5CouEt4ffCin_FpKUvXEYeknFU0Jd2_2-9z0swgmIJSINKNi2Av4g8CAv

### POST PRODUCT
POST http://localhost:8080/academics/api/product/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJMYXVyYTAxIiwiaWF0IjoxNzM3MjE4OTUyLCJleHAiOjE3MzcyMjI1NTJ9.MgwMiVFuOmYuiWgzuD62jCwKopWLJ4rbgrWTbJ5UslUUtgbHoeygTQKrLkEhvJhN

{
  "name": "Product 1",
  "category": "Category 1",
  "limite": "15",
  "stock": 5,
  "price": 10.0,
  "warehouseId": 1
}

### GET VOLUMS
GET http://localhost:8080/academics/api/volume/
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJMYXVyYTAxIiwiaWF0IjoxNzM3MjEzNTgxLCJleHAiOjE3MzcyMTcxODF9.YHrOOo37G4AnkOcB8HUG1FfL5Xe6QDsw1vyaoi3nZcssdVrTkEOo4wiA_Uc1Yr9a



### Enroll Employee in Volume
POST http://localhost:8080/academics/api/volume/enrollEmployee
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJKb2huIiwiaWF0IjoxNzM3MjI1MzY0LCJleHAiOjE3MzcyMjg5NjR9.1Q-ZenVpgHAuq15bv85zKVfHmacX524BFBteZ5u0vMtNKJ0EHTaSX1XSe1YKOL7L

{
  "id" : 2,
  "employeeUsername" : "John"
}


### POST ORDER
POST http://localhost:8080/academics/api/order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJNYXJpb3ppbiIsImlhdCI6MTczNzIyNTMxNiwiZXhwIjoxNzM3MjI4OTE2fQ.gACEYI2I-M9BmHMGrPO0BhOzNE0iGmWpKrwZVUZWrTRFlFL3lljvcKrU0iRwD9G1

{
  "usernameClient": "Mariozin",
  "morada": "Rua do Cardal",
  "precoTotal": 44.0,
  "products": [
    {
      "productId": 1,
      "amount": 7
    },
    {
      "productId": 3,
      "amount": 3
    }
  ]
}


###PATCH VALUE
PATCH http://localhost:8080/academics/api/sensor/1
Content-Type: application/json

{
  "valor": 15
}

###GET orders by client
GET http://localhost:8080/academics/api/client/Mariozin/orders
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJNYXJpb3ppbiIsImlhdCI6MTczNzIyODAzMywiZXhwIjoxNzM3MjMxNjMzfQ.FAsRgkHmqTc2lhZrSnDxmIRBuT5YQiOO-2eR9B9FuV-VyFg89PU0uk4kF9NqqBhE


###PUT product
PUT http://localhost:8080/academics/api/product/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJMYXVyYTAxIiwiaWF0IjoxNzM3MjEyNzQyLCJleHAiOjE3MzcyMTYzNDJ9.XajX6RINhD3Pe6LZVYDi1uiPUnsGEH6rqBlAQzTlto-jrx2MvfMTvT9oQNE5uSHa

{
    "name": "Teste",
    "category": "Eletrodoméstico",
    "limite": 100,
    "stock": 50,
    "price": 199.99,
    "warehouseId": 1
}
###GET volums by warehouseIdEmployee
GET http://localhost:8080/academics/api/employee/1/volumes
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJKb2huIiwiaWF0IjoxNzM3MjI2Mjg5LCJleHAiOjE3MzcyMjk4ODl9.DaVwqy4MhK2ZVkEbusIhsm7xT20gUY-47kN7i6mfzr7zetQ6U7G6ujrqBDciIcqN


###GET ALL VOLUMS (AS MANAGER)
GET http://localhost:8080/academics/api/volume/
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJMYXVyYTAxIiwiaWF0IjoxNzM3MjI1NDY3LCJleHAiOjE3MzcyMjkwNjd9.VnxkEZTqeuSKX0BeVxn7ihxvkMVT4FJ-UbTmsQC23HvkzDt1Qi0G77xTn782zvrN


###GET EMPLOY
GET http://localhost:8080/academics/api/employee/John
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJKb2huIiwiaWF0IjoxNzM3MjI3MzgwLCJleHAiOjE3MzcyMzA5ODB9.ZWH5lc8SRo_nozrXicg8R7rAlRiKaPBqTRRbBwH1h1K8SPakD8bIy95cTGJFF0Of

