### REQUEST JWT TOKEN
POST http://localhost:8080/academics/api/auth/login
Content-Type: application/json
Accept: application/json

{ "username": "Laura01", "password": "123" }

### Get Authenticated User
GET http://localhost:8080/academics/api/auth/user
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJMYXVyYTAxIiwiaWF0IjoxNzM3MTU1NjcxLCJleHAiOjE3MzcxNTkyNzF9.YCO0rakQAI5XIqSCWZupu3sYHm_WVfXQPfju0_kKPu0QZ1qEmSMG1OmQYg0lzZl6


### GET PRODUCTS
GET http://localhost:8080/academics/api/product/
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJNYXJpb3ppbiIsImlhdCI6MTczNzE1NDQ3OSwiZXhwIjoxNzM3MTU4MDc5fQ.8WpXbke5CouEt4ffCin_FpKUvXEYeknFU0Jd2_2-9z0swgmIJSINKNi2Av4g8CAv

### POST PRODUCT
POST http://localhost:8080/academics/api/product/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJNYXJpb3ppbiIsImlhdCI6MTczNzE1NDQ3OSwiZXhwIjoxNzM3MTU4MDc5fQ.8WpXbke5CouEt4ffCin_FpKUvXEYeknFU0Jd2_2-9z0swgmIJSINKNi2Av4g8CAv

{
  "code": 3,
  "name": "Product 1",
  "category": "Category 1",
  "limite": "15",
  "stock": 5,
  "price": 10.0,
  "warehouseId": 1
}

### GET VOLUMS
GET http://localhost:8080/academics/api/volume/
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJMYXVyYTAxIiwiaWF0IjoxNzM3MTU1NjcxLCJleHAiOjE3MzcxNTkyNzF9.YCO0rakQAI5XIqSCWZupu3sYHm_WVfXQPfju0_kKPu0QZ1qEmSMG1OmQYg0lzZl6



### Enroll Employee in Volume
POST http://localhost:8080/academics/api/volume/enrollEmployee
Content-Type: application/json

{
  "id" : 2,
  "employeeUsername" : "John"
}


### POST ORDER
POST http://localhost:8080/academics/api/order
Content-Type: application/json

{
  "usernameClient": "Mariozin",
  "morada": "Rua do Cardal",
  "precoTotal": 44.0,
  "products": [
    {
      "productId": 1,
      "amount": 7
    }
  ]
}

###PATCH VALUE
PATCH http://localhost:8080/academics/api/sensor/1
Content-Type: application/json

{
  "valor": 15
}

###GET orders by client
GET http://localhost:8080/academics/api/client/Mariozin/orders
Accept: application/json

