### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###



###GET PRODUCTS
GET http://localhost:8080/academics/api/product/
Accept: application/json